name = "blog"
compatibility_date = "2023-10-30"
main = "./functions/api/[[path]].js"

# Configure Cloudflare Pages with Functions
[build]
command = "npm run build"

[site]
bucket = "./dist"

# KV namespace for bookmark views
# You'll need to create this KV namespace in the Cloudflare dashboard
# and replace the id below with your actual KV namespace ID
[[kv_namespaces]]
binding = "BOOKMARK_VIEWS"
id = "b5a85846b3654eadb2eb27c98d3706f9"
preview_id = "dc78fa485d474f9aa61979fc9f086aa1"
